version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: realtimechat_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: realtimechat
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: realtimechat_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata: {}

